apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  labels:
    flex-volume-size: "10000000000"
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "1"
    limits.memory: 1Gi
