apiVersion: v1
kind: Pod
metadata:
  name: read-write-dataset
  labels:
    app: read-write-dataset
spec:
  containers:
  - image: busybox
    command: [/bin/sh, -c, 'cat /dataset/test.txt; echo "foo" > /dataset/test.txt; cat /dataset/test.txt; sleep 3600']
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - name: dataset
      mountPath: /dataset
  restartPolicy: Always
  volumes:
  - name: dataset
    flexVolume:
      driver: "nerdalize.com/dataset"
      options:
        input/s3Bucket: nlz-datasets-dev
        input/s3Key: test-helloworld.zip